# Gemini API and Model Settings
gemini_settings:
  available_base_models:
    - "gemini-2.0-flash"       # A good default, fast and capable
    - "gemini-2.0-flash-lite"
    - "gemini-2.5-pro-preview-05-06"


  default_base_model: "gemini-2.0-flash"

  default_generation_parameters:
    temperature: 0.7
    top_p: 0.9
    top_k: 40
    max_output_tokens: 2048

# Database Configuration
database:
  echo_sql: false # Set to true for SQLAlchemy to log all SQL statements (for debugging)

# Default Application Behavior
default_bot_behavior:
  group_chat_mode: "individual" # Default mode for new groups
  random_reply_enabled_in_shared_mode: true
  default_private_prompt_key: "none_prompt" # Refers to a key in prompts.yml or database (for private chats)
  default_group_role_prompt_key: "neutral_group_member" # Refers to a key for a group_role_payload in prompts.yml

# Group Chat Specific Settings
group_chat_settings:
  default_system_headers_template: |
    === SYSTEM HEADERS ===
    INPUT_FORMAT: "{username}: {message_content}"
    AI_BEHAVIOR: 作为群成员自然参与聊天，随时可以插话回复
    RESPONSE_MODE: 直接发送你想表达的内容
    === END_HEADERS ===
    PAYLOAD (角色扮演设定)
    {USER_CUSTOM_ROLE_PROMPT}
  random_reply_parameters:
    listen_message_count: 7
    base_probability_p_denominator: 25

# Logging Configuration
logging:
  level: "INFO" # Changed from DEBUG for less verbosity by default
  file_path: "logs/bot.log"
  max_bytes: 10485760 # 10MB
  backup_count: 5