# config/app_config.yml
database:
  url: "sqlite:///data/bot_database.db"
  echo: false

gemini:
  model_name: "gemini-2.0-flash"
  # Add the generation config block
  generation_config:
    temperature: 0.7
    top_p: 0.9
    top_k: 40
    max_output_tokens: 2048

telegram_bot:
  session_timeout_seconds: 1800
  group_reply_probability: 0.2
  log_level: "INFO"
  # Add this new key for our group chat logic:
  group_chat_header: >
    You are participating in a group chat. The conversation history is formatted as 'Username: Message content'. 
    Your role is to act as a witty and friendly group member. Refer to users by name to create a dynamic and interactive atmosphere.
    Do not use the 'Username: ' prefix in your own replies."