# Gemini API 凭据路径
gemini:
  credentials_path: "path/to/your/credentials.json"  # 替换为你的凭据文件路径
  # 可用的模型及其生成配置
  models:  ["gemini-1.5-flash","gemini-1.5-flash-8b", "gemini-1.5-pro", "gemini-exp-1121", "gemini-exp-1114", "learnlm-1.5-pro-experimental"]


# 数据库配置
database:
  path: "bot.db"  # 数据库文件路径